services:
  - type: web
    name: your-app-backend
    env: node
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # You'll set this in Render dashboard
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://your-frontend-url.onrender.com

  - type: web
    name: your-app-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        value: https://your-backend-url.onrender.com/api 